"""add phone numb

Revision ID: 079c0906ee9a
Revises: 9fb0fcc3fe3e
Create Date: 2022-12-23 10:38:19.651829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079c0906ee9a'
down_revision = '9fb0fcc3fe3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
